org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
org.gradle.caching=false
org.gradle.parallel=false