arb-dir: lib/l10n
template-arb-file: app_de.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - de
  - en
  - ar
  - zh
  - fr
  - es
  - hi
  - pt
  - ru
  - ja
  - tr
  - it
  - ko
  - id
  - fa
nullable-getter: false