[build]
  base = "frontend/flutter_app"
  command = "bash netlify_build.sh"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/timer"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/tasks"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/statistics"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/settings"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/account"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/auth/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/reset-password"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"